version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:  #追加
      - 33060:3306

  #追記
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    ports:
      - 3000:80
    volumes:
      - pma-session-store:/sessions

volumes:
  db-store:
  # 追記
  pma-session-store: